module.exports={
    facebook_1:{
        user_name:"carsyn.toluwanimi@lcelandic.com",    
        password:"bewa123$"
    },
    google_1:{
        user_name:"bewakoofandroid@gmail.com",
        password:"bewa123$"
    }
}